"""Reply formatting templates for Discord-facing outputs."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class ReplyTemplateSettings:
    include_ooc_notice: bool = False
    ooc_notice: str = "Generated by Homunculus."

    def __post_init__(self) -> None:
        if not self.ooc_notice.strip():
            raise ValueError("ooc_notice cannot be empty.")


class ReplyFormatter:
    """Formats NPC replies with a stable in-character message template."""

    def __init__(self, settings: ReplyTemplateSettings | None = None) -> None:
        self._settings = settings or ReplyTemplateSettings()

    def format_reply(self, *, npc_name: str, response_text: str) -> str:
        speaker = npc_name.strip() if npc_name.strip() else "NPC"
        body = response_text.strip()
        formatted = f"**{speaker}:** {body}" if body else f"**{speaker}:**"
        if self._settings.include_ooc_notice:
            formatted = f"{formatted}\n\n_OOC: {self._settings.ooc_notice}_"
        return formatted
